### ISSUE TITLE
all_partitions very slow

### ISSUE THREAD

**Issue by johannspies** [scheinerman/SimplePartitions.jl#1]
```
using ShowSet
using SimplePartitions
v  = 1:10
@time p = all_partitions(Set(v));
length(p)
```
 10.146464 seconds (34.66 M allocations: 3.269 GiB, 59.76% gc time)
115975

And in Python with these two functions: 
```

# From codereview.stackexchange.com                    
def partitions(set_):
    if not set_:
        yield []
        return
    for i in range(2**len(set_)//2):
        parts = [set(), set()]
        for item in set_:
            parts[i&1].add(item)
            i >>= 1
        for b in partitions(parts[1]):
            yield [parts[0]]+b

def get_partitions(set_):
    for partition in partitions(set_):
        yield [list(elt) for elt in partition]

%timeit p = get_partitions([1,2,3,4,5,6,7,8,9,10])
```
The slowest run took 4.77 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 325 ns per loop

**Comment by scheinerman** [comment]
This is interesting. One difference is that the Python code creates a generator and the Julia code creates the actual set of partitions. Still, the Python code is faster even if the last line is replaced by this:
`%timeit p = [t for t in get_partitions([1,2,3,4,5,6,7,8,9,10])]` 
I'd be happy for someone to re-implement this for the module. I'm no coding expert!
